FROM composer:1.7 as composer
FROM php:7.2-fpm-alpine

RUN set -ex \
        && apk add --no-cache --virtual .build-deps \
                coreutils \
                freetype-dev \
                libjpeg-turbo-dev \
                libpng-dev \
                libxml2-dev \
                libedit-dev \
                autoconf \
                gcc libc-dev libtool make \
                icu-dev \
                rabbitmq-c \
                rabbitmq-c-dev \
                imagemagick \
                imagemagick-dev \
                pdftk \
        && docker-php-ext-configure gd \
                --with-freetype-dir=/usr/include/ \
                --with-jpeg-dir=/usr/include/ \
                --with-png-dir=/usr/include/ \
        && docker-php-ext-configure intl \
        && docker-php-ext-install -j "$(nproc)" \
                gd \
                opcache \
                pdo_mysql \
                zip \
                readline \
                bcmath \
                intl  \
        && pecl install -f redis-4.1.1 \
        && pecl install -f amqp-1.9.3 \
        && pecl install -f imagick-3.4.3 \
        && docker-php-ext-enable \
                redis \
                imagick \
        && runDeps="$( \
                scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
                        | tr ',' '\n' \
                        | sort -u \
                        | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
        )" \
        && apk add --virtual .symfony-phpexts-rundeps $runDeps \
        && apk del .build-deps

RUN { \
                echo 'opcache.memory_consumption=128'; \
                echo 'opcache.interned_strings_buffer=8'; \
                echo 'opcache.max_accelerated_files=4000'; \
                echo 'opcache.revalidate_freq=60'; \
                echo 'opcache.fast_shutdown=1'; \
                echo 'opcache.enable_cli=1'; \
        } > /usr/local/etc/php/conf.d/opcache-recommended.ini

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /srv/app
